#!/bin/bash
if test $# != 1; then echo usage: $0 template_name; exit 1
elif test -d ./templates/$1; then echo $1 already exists!; exit 2; fi

mkdir -p ./templates/$1
cd templates/$1
cat > zh.txt << 'EOF'
这是一个中文模板示例。你可以根据需要写出略微不同的信件。比如：${sal}好，${name}，我$([ "$isClose" = y ] && echo 想告诉你一个小秘密 || echo 有一件事要告知你)。
EOF
cat > en.txt << 'EOF'
This is an English template demo. You can write slightly different letters according to your need. For example: Hi ${name}, I $([ "$isClose" = y ] && echo have a secret to tell you || echo would like to inform you of an affair).
EOF
echo "中文标题" > subject_zh.txt

echo "English Subject" > subject_en.txt

echo Template $1 created! See ./templates/$1
